# fly.toml app configuration file generated for rust-quest-runner on 2023-12-02T11:18:09+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rust-quest-runner"
primary_region = "mad"

[build]

[env]
  RUNNER_ADDRESS = "0.0.0.0"
  RUNNER_PORT = "3030"

[http_service]
  internal_port = 3030
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
